routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
Route::get('profiles', 'UserController@profile')->name('profiles');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::resource('settings', 'SettingController');



Route::resource('add-new-areas', 'AddNewAreaController');

Route::resource('areas', 'AreaController');

Route::resource('blocks', 'BlockController');
Route::get('blocks/create/{id}', 'BlockController@create');
Route::get('blocks/store/{id}', 'BlockController@store');

Route::resource('projects', 'ProjectController');

Route::resource('properties', 'PropertyController');
Route::get('properties/create/{id}', 'PropertyController@create');
Route::get('properties/store/{id}', 'PropertyController@store');

Route::resource('modes', 'ModeController');

Route::resource('schedules', 'ScheduleController');
Route::get('schedules/create/{id}', 'ScheduleController@create');
Route::get('schedules/store/{id}', 'ScheduleController@store');

Route::resource('custom-schedules', 'CustomScheduleController');

Route::resource('types', 'TypeController');

Route::resource('employees', 'EmployeeController');

Route::resource('clients', 'ClientController');

Route::resource('clients', 'ClientController');

Route::resource('employee-types', 'EmployeeTypeController');

Route::resource('designations', 'DesignationController');

//Route::get('/project/view', 'ProjectController@view');

Route::get('/project/view','ProjectController@view');
//Route::get('/project/view/1','ProjectController@welcome');


//Route::get('project/view', function ($view) {
////    return view('welcome');
////        return 'Hello';
//    return $view->id;
//});


Route::resource('inquiries', 'InquiryController');

Route::resource('bookings', 'BookingController');


Route::post('bookings/fetcharea', 'BookingController@fetcharea');

Route::post('bookings/fetchblock', 'BookingController@fetchblock');

Route::post('bookings/fetchproperty', 'BookingController@fetchProperties');

Route::resource('banks', 'BankController');

Route::resource('payments', 'PaymentController');
Route::get('payments/create/{id}', 'PaymentController@create');
Route::get('payments/store/{id}', 'PaymentController@store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/home.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-xs-4">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>{{ $users }}</h3>
                        <p>Users</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person"></i>
                    </div>
                    <a href="{{ route('admin.users.index') }}" class="small-box-footer">More info
                        <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-4">
                <!-- small box -->
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>{{ $roles }}</h3>
                        <p>Roles</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-android-document"></i>
                    </div>
                    <a href="{{ route('admin.roles.index') }}" class="small-box-footer">More info
                        <i class="fa fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
    </div>
@endsection