routes/admin.php
<?php


Auth::routes();

Route::get('/', 'HomeController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('dashboard');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
Route::get('about', 'HomeController@index');

Route::resource('roles', 'RoleController');

Route::resource('modules', 'ModuleController');

Route::get('/module/step1/{id?}', 'ModuleController@getStep1')->name('modules.create');
Route::get('/module/step2/{tablename?}', 'ModuleController@getStep2')->name('modules.create');
Route::get('/getJoinFields/{tablename?}', 'ModuleController@getJoinFields');
Route::get('/module/step3/{tablename?}', 'ModuleController@getStep3')->name('modules.create');

Route::post('/step1', 'ModuleController@postStep1');
Route::post('/step2', 'ModuleController@postStep2');
Route::post('/step3', 'ModuleController@postStep3');


Route::resource('users', 'UserController');

Route::resource('permissions', 'PermissionController');

//Route::resource('profile', 'UserController');

Route::get('user/profile', 'UserController@profile')->name('users.profile');
Route::get('profiles', 'UserController@profile')->name('profiles');
//Route::patch('users/profile-update/{id}', 'UserController@profileUpdate')->name('users.profile-update');

Route::resource('languages', 'LanguageController');

Route::resource('pages', 'PageController');

Route::resource('contactus', 'ContactUsController');

Route::resource('notifications', 'NotificationController');

Route::resource('menus', 'MenuController');

//Menu #TODO need to be fixed
Route::get('statusChange/{id}', 'MenuController@statusChange');

Route::resource('settings', 'SettingController');



Route::resource('add-new-areas', 'AddNewAreaController');

Route::resource('areas', 'AreaController');

Route::resource('blocks', 'BlockController');
Route::get('blocks/create/{id}', 'BlockController@create');
Route::get('blocks/store/{id}', 'BlockController@store');

Route::resource('projects', 'ProjectController');

Route::resource('properties', 'PropertyController');
Route::get('properties/create/{id}', 'PropertyController@create');
Route::get('properties/store/{id}', 'PropertyController@store');

Route::resource('modes', 'ModeController');

Route::resource('schedules', 'ScheduleController');
Route::get('schedules/create/{id}', 'ScheduleController@create');
Route::get('schedules/store/{id}', 'ScheduleController@store');

Route::resource('custom-schedules', 'CustomScheduleController');

Route::resource('types', 'TypeController');

Route::resource('employees', 'EmployeeController');

Route::resource('clients', 'ClientController');

Route::resource('clients', 'ClientController');

Route::resource('employee-types', 'EmployeeTypeController');

Route::resource('designations', 'DesignationController');

//Route::get('/project/view', 'ProjectController@view');

Route::get('/project/view','ProjectController@view');
//Route::get('/project/view/1','ProjectController@welcome');


//Route::get('project/view', function ($view) {
////    return view('welcome');
////        return 'Hello';
//    return $view->id;
//});


Route::resource('inquiries', 'InquiryController');

Route::resource('bookings', 'BookingController');


Route::post('bookings/fetcharea', 'BookingController@fetcharea');

Route::post('bookings/fetchblock', 'BookingController@fetchblock');

Route::post('bookings/fetchproperty', 'BookingController@fetchProperties');

Route::resource('banks', 'BankController');

Route::resource('payments', 'PaymentController');
Route::get('payments/create/{id}', 'PaymentController@create');
Route::get('payments/store/{id}', 'PaymentController@store');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/EmployeeTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helper\BreadcrumbsRegister;
use App\DataTables\Admin\EmployeeTypeDataTable;
use App\Http\Requests\Admin;
use App\Http\Requests\Admin\CreateEmployeeTypeRequest;
use App\Http\Requests\Admin\UpdateEmployeeTypeRequest;
use App\Repositories\Admin\EmployeeTypeRepository;
use App\Http\Controllers\AppBaseController;
use Laracasts\Flash\Flash;
use Illuminate\Http\Response;

class EmployeeTypeController extends AppBaseController
{
    /** ModelName */
    private $ModelName;

    /** BreadCrumbName */
    private $BreadCrumbName;

    /** @var  EmployeeTypeRepository */
    private $employeeTypeRepository;

    public function __construct(EmployeeTypeRepository $employeeTypeRepo)
    {
        $this->employeeTypeRepository = $employeeTypeRepo;
        $this->ModelName = 'employee-types';
        $this->BreadCrumbName = 'Employee Types';
    }

    /**
     * Display a listing of the EmployeeType.
     *
     * @param EmployeeTypeDataTable $employeeTypeDataTable
     * @return Response
     */
    public function index(EmployeeTypeDataTable $employeeTypeDataTable)
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return $employeeTypeDataTable->render('admin.employee_types.index', ['title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for creating a new EmployeeType.
     *
     * @return Response
     */
    public function create()
    {
        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName);
        return view('admin.employee_types.create')->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Store a newly created EmployeeType in storage.
     *
     * @param CreateEmployeeTypeRequest $request
     *
     * @return Response
     */
    public function store(CreateEmployeeTypeRequest $request)
    {
        $employeeType = $this->employeeTypeRepository->saveRecord($request);

        Flash::success($this->BreadCrumbName . ' saved successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.employee-types.create'));
        } elseif (isset($request->translation)) {
            $redirect_to = redirect(route('admin.employee-types.edit', $employeeType->id));
        } else {
            $redirect_to = redirect(route('admin.employee-types.index'));
        }
        return $redirect_to->with([
            'title' => $this->BreadCrumbName
        ]);
    }

    /**
     * Display the specified EmployeeType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $employeeType = $this->employeeTypeRepository->findWithoutFail($id);

        if (empty($employeeType)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.employee-types.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $employeeType);
        return view('admin.employee_types.show')->with(['employeeType' => $employeeType, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Show the form for editing the specified EmployeeType.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $employeeType = $this->employeeTypeRepository->findWithoutFail($id);

        if (empty($employeeType)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.employee-types.index'));
        }

        BreadcrumbsRegister::Register($this->ModelName,$this->BreadCrumbName, $employeeType);
        return view('admin.employee_types.edit')->with(['employeeType' => $employeeType, 'title' => $this->BreadCrumbName]);
    }

    /**
     * Update the specified EmployeeType in storage.
     *
     * @param  int              $id
     * @param UpdateEmployeeTypeRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEmployeeTypeRequest $request)
    {
        $employeeType = $this->employeeTypeRepository->findWithoutFail($id);

        if (empty($employeeType)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.employee-types.index'));
        }

        $employeeType = $this->employeeTypeRepository->updateRecord($request, $employeeType);

        Flash::success($this->BreadCrumbName . ' updated successfully.');
        if (isset($request->continue)) {
            $redirect_to = redirect(route('admin.employee-types.create'));
        } else {
            $redirect_to = redirect(route('admin.employee-types.index'));
        }
        return $redirect_to->with(['title' => $this->BreadCrumbName]);
    }

    /**
     * Remove the specified EmployeeType from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $employeeType = $this->employeeTypeRepository->findWithoutFail($id);

        if (empty($employeeType)) {
            Flash::error($this->BreadCrumbName . ' not found');
            return redirect(route('admin.employee-types.index'));
        }

        $this->employeeTypeRepository->deleteRecord($id);

        Flash::success($this->BreadCrumbName . ' deleted successfully.');
        return redirect(route('admin.employee-types.index'))->with(['title' => $this->BreadCrumbName]);
    }
}

resources/views/admin/employee_types/create.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'admin.employee-types.store', 'files' => true]) !!}

                        @include('admin.employee_types.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/employee_types/datatables_actions.blade.php
{!! Form::open(['route' => ['admin.employee-types.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    @ability('super-admin' ,'employee-types.show')
    <a href="{{ route('admin.employee-types.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    @endability
    @ability('super-admin' ,'employee-types.edit')
    <a href="{{ route('admin.employee-types.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    @endability
    @ability('super-admin' ,'employee-types.destroy')
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
    ]) !!}
    @endability
</div>
{!! Form::close() !!}

resources/views/admin/employee_types/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $employeeType->name }} <small>{{ $title }}</small>
@endsection

@section('content')
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($employeeType, ['route' => ['admin.employee-types.update', $employeeType->id], 'method' => 'patch', 'files' => true]) !!}

                        @include('admin.employee_types.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/employee_types/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder'=>'Enter name']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    @if(!isset($employeeType))
        {!! Form::submit(__('Save And Add Translations'), ['class' => 'btn btn-primary', 'name'=>'translation']) !!}
    @endif
    {!! Form::submit(__('Save And Add More'), ['class' => 'btn btn-primary', 'name'=>'continue']) !!}
    <a href="{!! route('admin.employee-types.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/employee_types/index.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('admin.employee_types.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/admin/employee_types/show.blade.php
@extends('admin.layouts.app')

@section('title')
    {{ $title }}
@endsection

@section('content')
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    <dl class="dl-horizontal">
                        @include('admin.employee_types.show_fields')
                    </dl>
                    {!! Form::open(['route' => ['admin.employee-types.destroy', $employeeType->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        @ability('super-admin' ,'employee-types.show')
                        <a href="{!! route('admin.employee-types.index') !!}" class="btn btn-default">
                            <i class="glyphicon glyphicon-arrow-left"></i> Back
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'employee-types.edit')
                        <a href="{{ route('admin.employee-types.edit', $employeeType->id) }}" class='btn btn-default'>
                            <i class="glyphicon glyphicon-edit"></i> Edit
                        </a>
                        @endability
                    </div>
                    <div class='btn-group'>
                        @ability('super-admin' ,'employee-types.destroy')
                        {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', [
                            'type' => 'submit',
                            'class' => 'btn btn-danger',
                            'onclick' => "confirmDelete($(this).parents('form')[0]); return false;"
                        ]) !!}
                        @endability
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/employee_types/show_fields.blade.php
<!-- Id Field -->
<dt>{!! Form::label('id', 'Id:') !!}</dt>
<dd>{!! $employeeType->id !!}</dd>

<!-- Name Field -->
<dt>{!! Form::label('name', 'Name:') !!}</dt>
<dd>{!! $employeeType->name !!}</dd>

<!-- Created At Field -->
<dt>{!! Form::label('created_at', 'Created At:') !!}</dt>
<dd>{!! $employeeType->created_at !!}</dd>

<!-- Updated At Field -->
<dt>{!! Form::label('updated_at', 'Updated At:') !!}</dt>
<dd>{!! $employeeType->updated_at !!}</dd>

<!-- Deleted At Field -->
<dt>{!! Form::label('deleted_at', 'Deleted At:') !!}</dt>
<dd>{!! $employeeType->deleted_at !!}</dd>

resources/views/admin/employee_types/table.blade.php
@push('css')
    @include('admin.layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts')
    @include('admin.layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush